CREATE TABLE SCHOOL (
SCHOOL_ID VARCHAR2(40) PRIMARY KEY,
SCHOOL_NAME VARCHAR2(100),
ABOUT VARCHAR2(300)
)

CREATE TABLE SCHOOL_REFERENCE (
SCHOOL_ID VARCHAR2(40),
FACEBOOK VARCHAR2(100),
INSTAGRAM VARCHAR2(100),
TWITTER VARCHAR2(100),
LINKED_IN VARCHAR2(100),
PINTEREST VARCHAR2(100)
)

CREATE TABLE 'CLASS' (
CLASS_ID VARCHAR2(40) PRIMARY KEY,
CLASS_NAME VARCHAR2(100)
)

CREATE TABLE SUBJECT (
SUBJECT_ID VARCHAR2(40) PRIMARY KEY,
SUBJECT_NAME VARCHAR2(50)
)

CREATE TABLE 'USER' (
USER_ID VARCHAR2(40),
SCHOOL_ID VARCHAR2(40),
EMAIL VARCHAR2(60) UNIQUE,
PASSWORD 
)

CREATE TABLE AGENDA_HEADER (
AGENDA_ID VARCHAR2(40),
AGENDA_DATE DATE DEFAULT SYSDATE,
TEACHER_ID
)

CREATE TABLE AGENDA_DETAIL (

)